apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gke-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
        - name:  gke-test-container
          image:LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:
          ports:
            - containerPort: 8080