apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gke-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
        - name:  gke-test-container
          image: us-central1-docker.pkg.dev/dark-sensor-386805/static-site:latest
          ports:
            - containerPort: 8080