apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: gke-test
  name: springdemo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: gke-test
    spec:
      imagePullSecrets:
      - name: my-docker-secret
      containers:
      - name: springdemo
        image: static-site
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
      restartPolicy: Always