apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test 
spec:
  selector:
    matchLabels:
      app: gke-test 
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app:gke-test 
    spec:
      containers:
       name: gke-test 
        image: 
        ports:
        - containerPort: 80